_:

[
  # Cloud / IaC / Kubernetes ecosystem
  "adembc/tap/lazyssh"
  "cloud-provider-kind"
  "cosign"
  "fluxcd/tap/flux"
  "hcloud"
  "helm"
  "helmfile"
  "k3d"
  "k6"
  "k9s"
  "kind"
  "kdash-rs/kdash/kdash"
  "kompose"
  "kor"
  "krew"
  "kubecm"
  "kubeconform"
  "kubernetes-cli"
  "kubectx"
  "kubent"
  "kubescape"
  "kustomize"
  "minikube"
  "opentofu"
  "popeye"
  "skopeo"
  "sops"
  "talosctl"
  "terragrunt"
  "tilt"
  "vcluster"

  # Development tools
  "act"
  "bruno-cli"
  "git"
  "git-flow-next"
  "gitlab-ci-local"
  "glab"
  "golangci-lint"
  "ijq"
  "jetbrains/junie/junie"
  "jj"
  "jq"
  "koji"
  "kubebuilder"
  "lnav"
  "markdownlint-cli"
  "mise"
  "operator-sdk"
  "oven-sh/bun/bun"
  "plantuml"
  "pnpm"
  "pre-commit"
  "prek"
  "richard-fairthorne/tap/pairqr"
  "skaffold"
  "ssh-audit"
  "tig"
  "trivy"
  "typst"
  "typstyle"
  "uv"
  "yq"

  # AI tools
  "anomalyco/tap/opencode"
  "brettdavies/tap/agentnative"
  "ast-grep"
  "backlog-md"
  "beads"
  "dolt" # beads dependency
  "mistral-vibe"
  "nono"
  "rtk"
  "rtk-ai/tap/icm"
  "rulesync"

  # System / shell / general utilities
  "carapace"
  "chezmoi"
  "coreutils"
  "darrylmorley/whatcable/whatcable-cli"
  "difftastic"
  "direnv"
  "dockutil"
  "duf"
  "dust"
  "felixkratz/formulae/sketchybar"
  "homebrew/brew-vulns/brew-vulns"
  "htop"
  "hyperb1iss/tap/unifly"
  "iproute2mac"
  "jordond/tap/jolt"
  # "koekeishiya/formulae/yabai"
  "macmon"
  "mas"
  "masawada/tap/macos-hid-inspector"
  "matthart1983/tap/netwatch"
  "matthart1983/tap/syswatch"
  "navi"
  "ncdu"
  "netfetch"
  "nmap"
  "pandoc"
  "pv"
  "sk" # skim-fuzzy-finder
  "virustotal-cli"
  "vivid"
  "zoxide"
]
